name: integratión
on: [push]
jobs:
  build:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          ls -la
          echo "hello world"
